import Head from "next/head";
import Image from "next/image";
import { useRouter } from "next/router";
import Link from "next/link";
import Layout from "src/components/Layout";

const Tabs = () => {
  const router = useRouter();
  return (
    <ul className="flex flex-wrap text-sm font-medium text-center text-gray-500 border-b border-gray-200 dark:border-gray-700 dark:text-gray-400">
      <li className="mr-2">
        <Link
          href="?tab=data"
          aria-current="page"
          className={`tab ${
            !router.query.tab || router.query.tab === "data" ? "active" : ""
          }`}
        >
          Data
        </Link>
      </li>
      <li className="mr-2">
        <Link
          href="?tab=chart"
          className={`tab ${router.query.tab === "chart" ? "active" : ""}`}
        >
          Chart
        </Link>
      </li>
    </ul>
  );
};

const tabMap = {
  data: <div>Data content</div>,
  chart: <div>Chart content</div>,
};

const Main = () => {
  const router = useRouter();

  return (
    <>
      <Tabs />
      {(router.query?.tab && tabMap[router.query.tab]) || null}
    </>
  );
};

export default function Page() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <Main />
      </Layout>
    </div>
  );
}
